version: '3.8'

services:

  frontend:
    build: ./frontend
    container_name: frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    command: npm run dev -- --host 0.0.0.0
    networks:
      - dev-net

  backend:
    build: ./backend
    container_name: backend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST_POSTGRES=postgres
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=appdb
    depends_on:
      - postgres
    networks:
      - dev-net

  postgres:
    image: postgres:16
    container_name: postgres-dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
<<<<<<< HEAD
=======
      - ./db/migrations:/migrations:ro
      - ./db/init:/docker-entrypoint-initdb.d:ro
>>>>>>> refactorizacion-y-testeo-de-algunas-cosas
    networks:
      - dev-net

  # 1. Tu MinIO principal (Igual que antes)
  minio:
    image: minio/minio
    container_name: minio-dev
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin_minio"
      MINIO_ROOT_PASSWORD: "password123"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - dev-net

  # 2. EL AUTOMATIZADOR (Crea el bucket privado y se apaga)
  minio-setup:
    image: minio/mc
    container_name: minio-setup
    depends_on:
      - minio
    networks:
      - dev-net
    entrypoint: >
      /bin/sh -c "
      echo 'Esperando a que MinIO inicie...';
      sleep 5;
      
      echo 'Conectando a MinIO...';
      mc alias set myminio http://minio:9000 admin_minio password123;
      
      echo 'Creando bucket privado observatory-files...';
      mc mb myminio/observatory-files || true;
      
      echo 'Configuración terminada. El bucket es seguro y hermético.';
      exit 0;
      "

volumes:
  minio_data:
 

networks:
  dev-net:
    driver: bridge
