version: '3.8'

services:

  frontend:
    build: ./frontend
    container_name: frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    command: npm run dev -- --host 0.0.0.0
    networks:
      - dev-net

  backend:
    build: ./backend
    container_name: backend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST_POSTGRES=postgres
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=appdb
    depends_on:
      - postgres
    networks:
      - dev-net

  postgres:
    image: postgres:16
    container_name: postgres-dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/migrations
    networks:
      - dev-net

  minio:
    image: minio/minio
    container_name: minio-dev
    ports:
      - "9000:9000" # Puerto de la API (S3)
      - "9001:9001" # Puerto del Panel de Administración Web
    environment:
      MINIO_ROOT_USER: "admin_minio"
      MINIO_ROOT_PASSWORD: "password123"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

# Al final de tu archivo, asegúrate de declarar el volumen (junto al de postgres)
volumes:
  minio_data:
 

networks:
  dev-net:
    driver: bridge
