\ir migrations/034_file_formats.sql
\ir migrations/002_create_roles.sql
\ir migrations/003_create_permissions.sql
\ir migrations/019_create_categories.sql
\ir migrations/020_create_licenses.sql
\ir migrations/024_create_tags.sql
\ir migrations/029_create_ods_objectives.sql
\ir migrations/005_create_accounts.sql
\ir migrations/011_create_role_permissions.sql
\ir migrations/001_create_aws_file_references.sql
\ir migrations/004_create_institutions.sql
\ir migrations/013_seed_roles.sql
\ir migrations/014_seed_permissions.sql
\ir migrations/015_seed_role_permissions.sql
\ir migrations/006_create_auth_sessions.sql
\ir migrations/007_create_verification_codes.sql
\ir migrations/008_create_password_reset_tokens.sql
\ir migrations/009_create_security_logs.sql
\ir migrations/021_create_dataset.sql
\ir migrations/022_create_dataset_account_permission.sql
\ir migrations/023_create_dataset_requests.sql
\ir migrations/025_dataset_tags.sql
\ir migrations/026_dataset_files.sql
\ir migrations/027_dataset_stats.sql
\ir migrations/028_dataset_events.sql
\ir migrations/030_create_news_posts.sql
\ir migrations/031_create_news_post_files.sql
\ir migrations/032_create_contact_messages.sql
\ir migrations/033_create_contact_message_files.sql
\ir migrations/035_seed_categories.sql
\ir migrations/036_seed_tags.sql
\ir migrations/037_seed_file_formats.sql
\ir migrations/038_seed_ods_objectives.sql
\ir migrations/039_seed_licenses.sql
\ir migrations/040_add_foreign_keys.sql